"""add url, location, external_id, posted_at to job_descriptions

Revision ID: 2e27e6298985
Revises: 4c2489e53b9c
Create Date: 2026-07-10 21:23:57.512389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e27e6298985'
down_revision: Union[str, Sequence[str], None] = '4c2489e53b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('url', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('location', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_job_descriptions_user_source_external_id', 'job_descriptions', ['user_id', 'source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_descriptions_user_source_external_id', 'job_descriptions', type_='unique')
    op.drop_column('job_descriptions', 'posted_at')
    op.drop_column('job_descriptions', 'external_id')
    op.drop_column('job_descriptions', 'location')
    op.drop_column('job_descriptions', 'url')
    # ### end Alembic commands ###
