"""add ON DELETE CASCADE to child foreign keys

Revision ID: 4c2489e53b9c
Revises: 7f0833c7b729
Create Date: 2026-07-08 01:31:32.193787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2489e53b9c'
down_revision: Union[str, Sequence[str], None] = '7f0833c7b729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_descriptions_user_id_fkey'), 'job_descriptions', type_='foreignkey')
    op.create_foreign_key(None, 'job_descriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('matches_resume_id_fkey'), 'matches', type_='foreignkey')
    op.drop_constraint(op.f('matches_job_description_id_fkey'), 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'job_descriptions', ['job_description_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'matches', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(op.f('matches_job_description_id_fkey'), 'matches', 'job_descriptions', ['job_description_id'], ['id'])
    op.create_foreign_key(op.f('matches_resume_id_fkey'), 'matches', 'resumes', ['resume_id'], ['id'])
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    op.create_foreign_key(op.f('job_descriptions_user_id_fkey'), 'job_descriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
